project:
  type: website
  output-dir: docs # 추가

website:
  title: "yeondu_blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/yenduhaeyo
format:
  html:
    theme:
      - litera
      - brand
    css: styles.css